// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartBudget.Infrastructure.Persistence;

#nullable disable

namespace SmartBudget.Infrastructure.Migrations
{
    [DbContext(typeof(SmartBudgetDbContext))]
    [Migration("20260618162631_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SmartBudget.Domain.Entities.BankAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('CHEQUING','SAVINGS','CREDIT')")
                        .HasDefaultValue("CHEQUING")
                        .HasColumnName("account_type");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("bank_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('CAD','USD','EUR')")
                        .HasDefaultValue("CAD")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_bank_accounts");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_bank_accounts_deleted_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_bank_accounts_user_id");

                    b.ToTable("bank_accounts", (string)null);
                });

            modelBuilder.Entity("SmartBudget.Domain.Entities.Budget", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("category_id")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("LimitAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("limit_amount");

                    b.Property<byte>("Month")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("month");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id")
                        .IsFixedLength();

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_budgets");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_budgets_category_id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_budgets_deleted_at");

                    b.HasIndex("Month")
                        .HasDatabaseName("ix_budgets_month");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_budgets_user_id");

                    b.HasIndex("UserId", "CategoryId", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("uq_budgets_user_category_period");

                    b.ToTable("budgets", (string)null);
                });

            modelBuilder.Entity("SmartBudget.Domain.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("char(7)")
                        .HasColumnName("color")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("❓")
                        .HasColumnName("icon");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<bool>("IsIncome")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_income");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_categories_deleted_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_categories_user_id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("SmartBudget.Domain.Entities.CategoryRule", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("category_id")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsRegex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_regex");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("keyword");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100)
                        .HasColumnName("priority");

                    b.Property<int>("Source")
                        .HasColumnType("int")
                        .HasColumnName("source");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_category_rules");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_category_rules_category_id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_category_rules_deleted_at");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_category_rules_priority");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_category_rules_user_id");

                    b.ToTable("category_rules", (string)null);
                });

            modelBuilder.Entity("SmartBudget.Domain.Entities.ImportBatch", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("BankAccountId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("bank_account_id")
                        .IsFixedLength();

                    b.Property<string>("BlobUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("blob_url");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DuplicateCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("duplicate_count");

                    b.Property<int>("ErrorCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("error_count");

                    b.Property<string>("ErrorMesage")
                        .HasColumnType("text")
                        .HasColumnName("error_mesage");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("enum('CSV','PDF')")
                        .HasColumnName("file_type");

                    b.Property<int>("ImporteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("importe_count");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("imported_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('PENDING','PROCESSING','COMPLETED','FAILED')")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<int>("TotalRows")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_rows");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_import_batches");

                    b.HasIndex("BankAccountId")
                        .HasDatabaseName("ix_import_batches_bank_account_id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_import_batches_deleted_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_import_batches_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_import_batches_user_id");

                    b.ToTable("import_batches", (string)null);
                });

            modelBuilder.Entity("SmartBudget.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("token");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SmartBudget.Domain.Entities.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("BankAccountId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("bank_account_id")
                        .IsFixedLength();

                    b.Property<string>("CategoryId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("category_id")
                        .IsFixedLength();

                    b.Property<string>("CleanLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("clean_label");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("hash")
                        .IsFixedLength();

                    b.Property<string>("ImportBatchId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("import_batch_id")
                        .IsFixedLength();

                    b.Property<bool>("IsCategoryManual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_category_manual");

                    b.Property<bool>("IsExcluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_excluded");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("note");

                    b.Property<string>("RawLabel")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("raw_label");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("enum('DEBIT','CREDIT')")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("BankAccountId")
                        .HasDatabaseName("ix_transactions_bank_account_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_transactions_category_id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_transactions_deleted_at");

                    b.HasIndex("ImportBatchId")
                        .HasDatabaseName("ix_transactions_import_batch_id");

                    b.HasIndex("TransactionDate")
                        .HasDatabaseName("ix_transactions_transaction_date");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_transactions_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_transactions_user_id");

                    b.HasIndex("Hash", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_transactions_hash_user");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("SmartBudget.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('CAD','USD','EUR')")
                        .HasDefaultValue("CAD")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<byte>("MonthStartDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("month_start_day");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_users_deleted_at");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SmartBudget.Domain.Entities.BankAccount", b =>
                {
                    b.HasOne("SmartBudget.Domain.Entities.User", "User")
                        .WithMany("BankAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bank_accounts_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartBudget.Domain.Entities.Budget", b =>
                {
                    b.HasOne("SmartBudget.Domain.Entities.Category", "Category")
                        .WithMany("Budgets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budgets_categories_category_id");

                    b.HasOne("SmartBudget.Domain.Entities.User", "User")
                        .WithMany("Budgets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budgets_users_user_id");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartBudget.Domain.Entities.Category", b =>
                {
                    b.HasOne("SmartBudget.Domain.Entities.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_categories_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartBudget.Domain.Entities.CategoryRule", b =>
                {
                    b.HasOne("SmartBudget.Domain.Entities.Category", "Category")
                        .WithMany("CategoryRules")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_rules_categories_category_id");

                    b.HasOne("SmartBudget.Domain.Entities.User", "User")
                        .WithMany("CategoryRules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_category_rules_users_user_id");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartBudget.Domain.Entities.ImportBatch", b =>
                {
                    b.HasOne("SmartBudget.Domain.Entities.BankAccount", "BankAccount")
                        .WithMany("ImportBatches")
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_import_batches_bank_accounts_bank_account_id");

                    b.HasOne("SmartBudget.Domain.Entities.User", "User")
                        .WithMany("ImportBatches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_import_batches_users_user_id");

                    b.Navigation("BankAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartBudget.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SmartBudget.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartBudget.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("SmartBudget.Domain.Entities.BankAccount", "BankAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_bank_accounts_bank_account_id");

                    b.HasOne("SmartBudget.Domain.Entities.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_transactions_categories_category_id");

                    b.HasOne("SmartBudget.Domain.Entities.ImportBatch", "ImportBatch")
                        .WithMany("Transactions")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_transactions_import_batches_import_batch_id");

                    b.HasOne("SmartBudget.Domain.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_users_user_id");

                    b.Navigation("BankAccount");

                    b.Navigation("Category");

                    b.Navigation("ImportBatch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartBudget.Domain.Entities.BankAccount", b =>
                {
                    b.Navigation("ImportBatches");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SmartBudget.Domain.Entities.Category", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("CategoryRules");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SmartBudget.Domain.Entities.ImportBatch", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SmartBudget.Domain.Entities.User", b =>
                {
                    b.Navigation("BankAccounts");

                    b.Navigation("Budgets");

                    b.Navigation("Categories");

                    b.Navigation("CategoryRules");

                    b.Navigation("ImportBatches");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
